version: "3.8"

services:
  auth:
    container_name: auth
    build:
      context: ./auth_hospital
      dockerfile: Dockerfile.dev
    ## Using this for test
    ports:
      - "5002:3000"
    volumes:
      - ./auth_hospital:/usr/src/app
    environment:
      - DATABASE_HOST=mongodb://172.17.0.1:27017/auth_db
      ## NOTE: 172.17.0.1 is my local ip address for docker to work with
    restart: "no"
    networks:
      - hospital

networks:
  hospital:
    driver: bridge
