apiVersion: skaffold/v3
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: netflams10/auth-service
      context: auth_hospital
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - dest: '**/*.ts'
            src: .

manifests:
  rawYaml:
  - ./k8/*
deploy:
  kubectl: {}
  
  

# command: skaffold dev